# SPDX-FileCopyrightText: 2025 Ben Jarvis
#
# SPDX-License-Identifier: Unlicense

title: chimera-nas
description: chimera-nas documentation
theme: just-the-docs
color_scheme: dark


url: https://chimeraproject.io/

aux_links:
  GitHub: https://github.com/chimera-nas/repositories
