FROM ubuntu:24.04

RUN apt-get -y update && \
    apt-get -y --no-install-recommends upgrade && \
    apt-get -y --no-install-recommends install unminimize && \
    echo y | unminimize && \
    apt-get -y --no-install-recommends install git ssh ruby-full build-essential zlib1g-dev && \
    gem install jekyll bundler
